### ISSUE TITLE
Add a  "More stories..." button at the bottom of the News segment

### ISSUE THREAD

**Issue by vdeparday** [GFDRR/opencities#104]
![image](https://user-images.githubusercontent.com/1036189/48380816-8e084b00-e6d9-11e8-98a7-cdb91507479d.png)

It should link to: https://opendri.org/tag/open-cities-africa/

**Comment by ppasq** [comment]
Done. Please close if it is ok.

**Comment by vdeparday** [comment]
Looks good, just a very small thing, on mobile I only see "Mo..." Any way to make it more explicit on mobile ?

**Comment by vdeparday** [comment]
Works. Thank you Paolo.
