### ISSUE TITLE
Touch-up on the logos

### ISSUE THREAD

**Issue by vdeparday** [GFDRR/opencities#107]
![image](https://user-images.githubusercontent.com/1036189/48571819-1ec46e00-e908-11e8-8ab3-3c7e70420f60.png)

The crews logo should go on the supported by. We should also add the cooperation belge on the supported by side.
For the initiative of should be first opendri, then gfdrr, then world bank.

**Comment by vdeparday** [comment]
in two columns it doesn't look very good. can we put them one line implemented by, next line supported by, etc...

**Comment by ppasq** [comment]
Ok @vdeparday, can you please also check if the link to the Belgian cooperation is correct?

**Comment by vdeparday** [comment]
yes it is. Thank you @ppasq

**Comment by ppasq** [comment]
Fixed.

**Comment by vdeparday** [comment]
Sorry to be really nit picky but the spacing with the last section is bigger and users may not see the last section.

![image](https://user-images.githubusercontent.com/1036189/48626197-8f739500-e9b1-11e8-8dec-dd9cdde1a865.png)

**Comment by ppasq** [comment]
You are right! I've missed to delete an inline rule. Thanks. Fixed.

**Comment by vdeparday** [comment]
Looks good. Thank you @ppasq
