### ISSUE TITLE
Organize analytics design of each city page 

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/opencities#11]
The three themes are:

1. Progress to Date
2. Data Quality
3. Community Dynamics

Corresponding sections with headers, description and widgets for each theme:

**1. Mapping Progress to Date**
This section provides and overview of mapping activities in the selected city geographic extent. The Before/After widget below allows comparing current density and distribution of map features with snapshots from previous years. The time chart of OSM editing activity over time offers insights on how many features have been contributed to the map over a specified period.

- [x] Visual Before/After Assessment (map widget)
- [x] Edits Over Time (time chart)
- [ ] Field Mapping Planning → MapCampaigner (internal to teams)
- [ ] Percent of Mapped features and Tags → density map widget, time chart?

**2. Data Quality**
While OSM coverage keeps increasing, it's important to also understand quality of the data created. The tools available in this section allow for comparing OSM data with other "reference" datasets. These could be, for example, official datasets from government agencies showing distribution of features with those available OSM. The "Gap Detection" widget provides a visual representation of potential gaps in data, by comparing the latest OSM buildings with built-up areas automatically detected from satellite imagery.

- [x] Compare with Other Datasets (Gap Detection widget)
- [ ] Geometry and Tagging Quality → osmlint processors, osma-health, MapCampaigner? 
- [ ] Identify Features added by New Mappers → “Editor Level of Experience” widget

**3. OSM Community Dynamics**
Understanding mapping progress and data quality also requires looking at the local OSM community and how mappers have contributed over time. Embedded widgets in this sections allow e.g. exploring the list of top mappers who contributed to features within the city extent, with links to their OSM user profile page. A time chart of number of user contributions over pre-defined time periods (daily, weekly, monthly), also provides a picture of how consistent the mapping activity in the area is.

- [x] Number of Contributing Mappers over Time (time chart of users)
- [x] Top Mappers and How to Learn More about them (chart of top mappers)
- [ ] Mappers retention → Ohsome history database and API?

Shall we put the "OSM OVERALL STATS" under one of the three themes, or just at the top of each page as general statistics?

**Comment by tyrasd** [comment]
> To embed “Gap Detection” widget

This works now. Just append `/embed` to the respective url to use it in an iframe. For example: `http://osm-analytics.org/#/gaps/bbox:-26.41553,-14.76801,78.35889,26.65571/buildings-vs-ghs/embed/opendri`

**Comment by cgiovando** [comment]
Hey @ppasq - I updated each theme description and marked those widgets that we should be able to include on launch. Can you reflect on the website and organize each city page with the three analytics sections? Thanks!

**Comment by cgiovando** [comment]
Some feedback from Grace on city pages design:

>Can we put a line under OPEN CITIES to give a little separation from the city and country name? Since Open Cities is the same font size as Country Name.
