### ISSUE TITLE
UAV Imagery Maps

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/opencities#116]
@ppasq - could you please add widgets like the one in Kampala for UAV imagery collected in other cities?

![screen shot 2019-01-29 at 18 32 27](https://user-images.githubusercontent.com/10201533/51927687-6bdabb00-23f4-11e9-91fc-e6641681b12c.jpg)

There are several mosaics in Accra and Zanzibar, and some in Kinshasa and Monrovia. Can multiple images be combined on the same map for each city?

Any other city with UAV imagery that I'm missing @vdeparday @gracedoherty ?

**Comment by vdeparday** [comment]
There should be some in Pointe-Noire, Ngaoundere, Antananarivo, but I am not sure if they uploaded it to OpenAerialMap. Do you have a good manual that @gracedoherty could send around to all the teams to make sure it is all uploaded ?

We should also have links for people to download or use TMS. Thanks you.

Note: for Uganda, it needs to be added on the Open Cities page too

**Comment by cgiovando** [comment]
Instructions for uploading into OpenAerialMap:

1.  Go to https://map.openaerialmap.org
2. Click on `Login` button in top right area
3. Choose Google or Facebook authentication
4. After authentication, click on `Upload` button in top right area
5. Fill out metadata and upload information for each orthomosaic

@gracedoherty let me know if people have problems with the upload process.

I will open separate tickets for the other two requests.

**Comment by cgiovando** [comment]
Accra --> https://map.openaerialmap.org/#/0/user/5ac6902d91b5310010e0d490?_k=jcz0ub (those with _Open Cities Africa_ in the title)

**Comment by gracedoherty** [comment]
**Saint-Louis** didn't take their own drone imagery. They did send me a link to the DG satellite imagery from 2018 that they've been using. Do we want to include it? I guess it depends how we phrase it on the site, as we don't want to imply that we financed the DG imagery capture.
https://map.openaerialmap.org/#/-16.458892822265625,16.022468319445952,13/square/033303000322?_k=khu4zy

**Comment by gracedoherty** [comment]
**Pointe-Noire**: 
https://map.openaerialmap.org/#/11.91141128540039,-4.816628095528716,12/square/300010220331213?_k=ez0iex
https://map.openaerialmap.org/#/11.898021697998047,-4.773520832778661,12/square/30001022033103?_k=h093k3

**Comment by cgiovando** [comment]
Ngaoundéré: https://map.openaerialmap.org/#/13.556785583496094,7.341015340601155,11/user/5c5a99cfaa451700058ff538?_k=hx0vqg

OpenCitiesNgaoundere_Djalingo_Sabongari3_Ortho and OpenCitiesNgaoundere_Mount_Ngaoundere_Ortho

**Comment by gracedoherty** [comment]
Kampala
https://map.openaerialmap.org/#/32.63144373893738,0.2616217581798175,16/square/122323332213010003?_k=8g110q

**Comment by ppasq** [comment]
Done. Any other imagery available?

**Comment by gracedoherty** [comment]
Seychelles: 
https://www.webgis.gov.sc/mapcache/tms/1.0.0/drone_imagery@Custom3857/{z}/{x}/{-y}.png

Cristiano says for Seychelles that the "TMS endpoint should be fine for the slippy map on city page." 

I've sent a couple emails to the Antananarivo team but still have not heard back. Once Seychelles is up we can close this issue, and I can make a new one for Antananarivo.

**Comment by ppasq** [comment]
Seychelles imagery has been added.
