### ISSUE TITLE
Split OSM Overall Stats into sections

### ISSUE THREAD

**Issue by gracedoherty** [GFDRR/opencities#117]
It would be nice to have sub-sections for “Features” and “Contributors.” Also we shouldn’t use “user” if we already have “contributor” in the next widget.

![image](https://user-images.githubusercontent.com/42003495/51941554-e995cb00-23e2-11e9-9cc5-f56fecf9137a.png)

@cgiovando @vdeparday @ppasq

**Comment by ppasq** [comment]
Done with #142.

**Comment by gracedoherty** [comment]
Thanks
