### ISSUE TITLE
Fix cities not showing on main map

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/opencities#12]
Kinshasa and Pointe Noire are not showing

As discussed, maybe remove dynamic map for now and use static screenshot?

**Comment by ppasq** [comment]
Added a static screenshot.

**Comment by vdeparday** [comment]
Can we make the city name clickable on the map?

**Comment by cgiovando** [comment]
> Can we make the city name clickable on the map?

This will probably be after launch, unless @ppasq has some quick ideas

In the meantime, we would still need to update the map with changes from #29

**Comment by cgiovando** [comment]
This should be done - creating #41 to track enhancements to the overview cities map
