### ISSUE TITLE
Add OSM slippy of the AOI on each page

### ISSUE THREAD

**Issue by vdeparday** [GFDRR/opencities#121]
Just realized that we don't have the map ! We could use HOT style, or a mapbox one. In terms of design, I think Paolo will have the best ideas.

**Comment by ppasq** [comment]
What about adding also aerial imagery maps (#116) in one viewer with multiple basemaps? Or do you prefer to have separate viewers?

**Comment by cgiovando** [comment]
Combined would be fine, but we need to consider the added weight to each page, especially if we use overlays with vector tiles. What's your estimate @ppasq ?

**Comment by vdeparday** [comment]
Thank you @ppasq for adding the interactive map. I am not sure if you are finished yet but I think it will need several improvement: 
- First i think we should use another rendering. Maybe, Mapbox Outdoor so that we have point of interest, buildings, and the terrain curves and shading. Because right now, it looks like the map is empty.
- We should remove the Drone map by default because it zooms on it and looks a bit weird.
- Then we should make it more obvious how to display the drone layer. Maybe we can have a sentence with a button just above ("add / remove drone layer). It may not be the most elegant
- Finally we should add a link to the OAM tiles too

Thank you !

cc @cgiovando @gracedoherty

**Comment by ppasq** [comment]
Here is a recap of what has been done:

- The Mapbox Outdoor has been added as basemap
- Aerial imagery has been removed by default
- A button to view/hide aerial imagery (where available) has been added

@vdeparday, @cgiovando would the link to [a selected OAM grid](https://map.openaerialmap.org/#/-16.458892822265625,16.022468319445952,13/square/033303000322?_k=khu4zy) be enough or should I add also #120 (e.g. as a table?)

**Comment by gracedoherty** [comment]
It looks really nice. 

For some of the cities (Accra, Pointe-Noire, maybe others) the aerial imagery only shows up when you increase the zoom level. Also Accra's imagery is showing up with a white background for some reason.

**Comment by vdeparday** [comment]
Agree with @gracedoherty it is a bit deceiving at first because the imagery doesn't appear when clicking on the button. Either we can make sure the image is seen at that zoom level without have to zoom in or we automatically zoom on the right area and right zoom level.

Also have the white background.

**Comment by vdeparday** [comment]
@ppasq I think linking to the selected OAM grid should work this way we don't have to keep updating the link. Does that make sense @cgiovando ?

**Comment by vdeparday** [comment]
We should also add higher zoom level for the map and drone imagery if possible

**Comment by vdeparday** [comment]
after checking more in details, I feel like we should switch to Mapbox Street and allow for a higher zoom level so that we can see better the richness of the data.

Could we move up the download data button to the side of the Show / Hide Aerial imagery ? And we can also put the download aerial imagery button there too.

**Comment by ppasq** [comment]
@vdeparday I've switched to MapBox streets, adjusted the initial position and zoom, and moved the download data button as requested. More comments in #120

**Comment by ppasq** [comment]
@gracedoherty, @vdeparday I'm afraid I have no control on the image white background. I think it depends on how the image was uploaded on OAM.

**Comment by vdeparday** [comment]
thank you @ppasq , @cgiovando any idea?

**Comment by vdeparday** [comment]
Thank you @ppasq for all the fixes. 
The UAV imagery still dissapear if I zoom out one notch. Can we make sure it stays at all zoom level ?

For some reasons the rendering doesn't show all the data (for instance Accra if you zoom in where the UAV imagery has been taken, it should be fully mapped). Is it because Mapbox tiles have not been updated? Or they are not rendered in this style? It still called Outdoor in the layer switcher but I think the layer is actually streets.

**Comment by ppasq** [comment]
I believe the images disappear because they are not available in OAM at some zoom levels. Maybe @cgiovando knows how to fix it in OAM?

I think that the MapBox Streets layer has not been updated. I've double checked with the corresponding vector map (streets-v9) and many buildings in that area are present instead. So I would try to switch from raster to vector tiles to get the most recent updates.

I'm going to fix the Outdoor label as well. Thanks.

**Comment by ppasq** [comment]
@vdeparday I've switched all city maps (except Seychelles) to vector tiles. Please double check and in case close this issue. In the meantime I'm opening an issue #162 for the Seychelles map.
