### ISSUE TITLE
Update Brazzaville AOI

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/opencities#127]
New AOI --> https://gist.github.com/cgiovando/122c8007c993054470d0ce513077a027

To update widgets and stats on https://opencitiesproject.org/brazzaville/

**Comment by ppasq** [comment]
Done. Please note that [OSM Analytics Api](https://github.com/GFDRR/osm-analytics-api) does not support multi polygons for stats. However I've created unlikely polygons (especially for Brazzaville) as a workaround. Could it be a nice to have feature?

**Comment by cgiovando** [comment]
Thanks, @ppasq - What do you mean by "unlikely polygons"?

Can you please post this feature request in the OSMA API repo?

**Comment by ppasq** [comment]
The OSM Analytics API stats endpoint supports "polygon", "country" and "bbox". So I've transformed the gist links into polygons. But when separated areas are described (afaik) you need to connect the polygons. The result can be [something like this](https://osm-analytics.org/#/show/polygon:o~a%7CAtzcYbBcg%40v%40gPwBaOuNuTmbEs%7DC%60a%40yfAdLgE%60BiEhEkBlEsEG_D~%40yIvBsBfDr%40vD_%40lLgEtA%7CVvB%3F%7B%40nn%40u%7D%40oVwOxb%40oOhb%40zaE%60%7DChNxTbClOgAjPzXnD%7CGlCdFfAdCWnB%60DnJpEx%40hBfDtDtOpBrHbI%5EjA%7DAtBoAxAgEBaCeAiCyBeAhD%7DCdGgB%7B%40%7B%40WsAG_StE/buildings/recency).
