### ISSUE TITLE
Homepage loading is slowed down by RSS2HTML service

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/opencities#129]
As already mentioned in https://github.com/GFDRR/opencities/issues/8#issuecomment-459395573 the RSS2HTML service from https://rss.bloople.net causes the homepage to load very slow and making the side menu inaccessible until the RSS feed is loaded.

We should think of a different mechanism to pull articles from OpenDRI.org - or maybe just add a daily caching layer to reduce subsequent page loads.

Would a CDN (e.g. https://www.cloudflare.com/cdn/) help with this?

**Comment by ppasq** [comment]
The script has been changed. Let's test this for now.

**Comment by cgiovando** [comment]
Works great!
