### ISSUE TITLE
Issue with display on IE11 for Blog post

### ISSUE THREAD

**Issue by vdeparday** [GFDRR/opencities#144]
The font doesn't load.
And somehow the image is sideway ! Although it is fine on chrome

![image](https://user-images.githubusercontent.com/1036189/53528892-47552a00-3aeb-11e9-9fe0-e3f06beca17b.png)

**Comment by gracedoherty** [comment]
Messed around with the photo's settings and it seems to be fixed now.

![image](https://user-images.githubusercontent.com/42003495/53582146-ebbb8880-3b4c-11e9-9ebb-c691153722a8.png)
