### ISSUE TITLE
Embed gap detection widget in city pages

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/opencities#15]
@ppasq can you try embedding the gap detection tool? Here's an example:

http://osm-analytics.org/#/gaps/bbox:-26.41553,-14.76801,78.35889,26.65571/buildings-vs-ghs/embed/opendri

Please ask @tyrasd if you have questions on how it works.

Thanks!

**Comment by ppasq** [comment]
Added with PR #16 .

**Comment by cgiovando** [comment]
Widget was added - moving to later milestone for improvements to styling mentioned in above comment.
