### ISSUE TITLE
Small fixes on videos

### ISSUE THREAD

**Issue by vdeparday** [GFDRR/opencities#150]
Could we rename "Open Cities Africa - Tool Design for Urban Resilience" => "Open Cities 2nd Regional Meeting - Tool Design for Urban Resilience - Dar Es Salaam, Tanzania" ?

Also, do we have subtitles for them ? Maybe we can put a note about automatic subtitles.

I want to try to circulate all of them a bit more.

**Comment by gracedoherty** [comment]
As an update, I've been working to get these hosted on the GFDRR YouTube account so that we can close the Open Cities account. Will rename and add subtitles once they're up.

**Comment by gracedoherty** [comment]
Done:
- Uploaded both videos to GFDRR YouTube (and deleted on old account)
- Renamed both videos
- Added subtitles to second video
- Updated Open Cities homepage links
- Updated OpenDRI blog embedded links
