### ISSUE TITLE
Add Uganda Open Mapping atlas

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/opencities#155]
The Uganda Open Mapping [atlas](https://drive.google.com/file/d/1cuHgHGMs5umk9Q1jWVu3PUbAQsJ5VwlV/view) was published and should be linked on the project webpage at https://opencitiesproject.org/uganda/

We should also add a reference to the new blog post once posted on https://opendri.org/category/news/

Text in the project page may need to be changed from _EXPECTED OUTCOMES_ to _OUTCOMES_

**Comment by cgiovando** [comment]
I uploaded [web-optimized PDF](https://github.com/GFDRR/opencities/raw/gh-pages/uganda/Ggaba%20Atlas%20-%20Final%2020190408%20-%20Web%20Resolution.pdf) in Github, to link from the blog post [here](https://opendri.org/uganda-open-mapping-for-resilience-completes-ggaba-parish-pilot/). We should still update the Uganda page on the Open Cities website to reflect the latest project updates.

**Comment by ppasq** [comment]
@cgiovando I've added a link to download the Atlas and reference to the Ggaba blog post [in the Uganda page](https://opencitiesproject.org/uganda/).

**Comment by gracedoherty** [comment]
Closing this issue. Still unresolved is adding a reference to the blog post, which we are addressing for all cities in another issue (will link when created).
