### ISSUE TITLE
Unable to assign team members to issues

### ISSUE THREAD

**Issue by gracedoherty** [GFDRR/opencities#165]
I am not always able to tag @nualacowan and Mira in comments (e.g. @MiraLGupta is not an option for me in this issue comment, but she is in #157 ). Likewise, I am unable to assign issues to either of them.

Could someone with higher privileges on this repo please determine what is causing this? Do they have limited privileges?

**Comment by gracedoherty** [comment]
Update: I see that Mira was tagged even though she wasn't in the drop down list. However I'm still unable to assign issues to either of them.

**Comment by cgiovando** [comment]
I added both - let me know if now you cannot assign tasks to them

**Comment by gracedoherty** [comment]
I'm now able to assign to Nuala. Still unable to assign to Mira (and her name still does not appear in the drop-down list).

**Comment by cgiovando** [comment]
@MiraLGupta needs to accept the [invitation](https://github.com/GFDRR/opencities/invitations) to join this repo before you can assign her

![Screen Shot 2019-05-31 at 14 58 48](https://user-images.githubusercontent.com/10201533/58707282-b8d79980-83b4-11e9-8383-4d7150ffde22.jpg)
