### ISSUE TITLE
Better quality images for homepage’s “A Collaborative Approach”

### ISSUE THREAD

**Issue by enockseth** [GFDRR/opencities#170]
The left one exists in better quality. The right one should be replaced.
![](https://opencitiesproject.org/images/collaborative2.jpg)

**Comment by enockseth** [comment]
@gracedoherty kindly share link for the left image in good quality and alternate image to be used to replace the right one.

**Comment by gracedoherty** [comment]
Left (higher quality, same image):
https://drive.google.com/file/d/1Q7wrH5rHZyA7yl89uxfmiNenQ9eblAc7/view?usp=sharing

Right (replacement, with new acknowledgement):
https://drive.google.com/file/d/16Bs-j9brMiCac1Zyz8z2Txw7EIECEyxS/view?usp=sharing
© ACAGER

**Comment by enockseth** [comment]
#191
