### ISSUE TITLE
Blog posts not appearing on home page

### ISSUE THREAD

**Issue by gracedoherty** [GFDRR/opencities#173]
The blogs from https://opendri.org/tag/open-cities-africa/ are not appearing in the Blog Posts & Videos section of the home page. There should be ~5 posts listed (or however many it takes to reach the bottom of the videos list) followed by the "More Stories" button.

![image](https://user-images.githubusercontent.com/42003495/67345830-fa9ee300-f501-11e9-8974-d62c868cabe0.png)

**Comment by ppasq** [comment]
@gracedoherty I'm not getting this issue. Could you pls check again?
![Screenshot 2019-10-23 at 10 18 45](https://user-images.githubusercontent.com/3024454/67372744-ab4ac800-f57e-11e9-89c8-3860e7a66e2b.png)

**Comment by gracedoherty** [comment]
@vdeparday It's showing up now on Chrome and IE for me. If it's fine for you too, please close the issue. If not, could you give details on your browser, etc.

**Comment by gracedoherty** [comment]
@vdeparday I will close this issue. Please reopen if you are still having this problem.
