### ISSUE TITLE
Can we add implementing partners at the bottom

### ISSUE THREAD

**Issue by vdeparday** [GFDRR/opencities#18]
Could we add another section in a different color at the bottom below the Initiative of / Funded by with the following logos and hyperlink to websites:

HOT https://www.hotosm.org/
Mobile Web Ghana https://mobilewebghana.org/
Ilab Liberia https://www.ilabliberia.org/
ImmerGIS http://immergis.fr/en/
BEST (couldn't find a website but here is their logo :
Habaka https://habaka.org/
OFSAC: https://www.osfac.net/
MapUganda: https://www.osfac.net/
Spatial Collective: http://spatialcollective.com/
AllSpatial: https://www.allspatial.sc/
Acager: http://acager.org/ 
Sogefi Cameroon: http://sogefi.cm/
Ithaca: http://www.ithacaweb.org/ 

We could also add them to the relevant cities at the bottom?

**Comment by vdeparday** [comment]
Two more: 
University Marien Ngouabi
https://www.umng.cg/

Ucac-Icam
https://www.ucac-icam.com/ucac-icam/nos-campus/pointe-noire/

**Comment by cgiovando** [comment]
Hi @ppasq - see the list of logos and links to partners' websites here: https://github.com/cgiovando/opencities/blob/gh-pages/_includes/footer.html

I wasn't able to add them properly to the footer / bottom area. I'll let you work the design and code ;)

**Comment by vdeparday** [comment]
@ppasq this one should be easy. Could you look at so that it is implemented as soon as possible ? Ithaca should be added to the list too ;)

**Comment by ppasq** [comment]
Done. Although some logos have poor quality. Please open another issue if you can provide better logos.

**Comment by vdeparday** [comment]
It is looking good ! Could we add an item in the menu "Partners" that would slide down to that section ?

Thank you !
