### ISSUE TITLE
OSM stats not appearing. 

### ISSUE THREAD

**Issue by gracedoherty** [GFDRR/opencities#186]
The numbers are not populating in the OSM stats widget on any of the city pages.
![image](https://user-images.githubusercontent.com/42003495/85325286-fc55e780-b490-11ea-9de6-649f7a7726e8.png)

**Comment by enockseth** [comment]
Thanks Grace, this doesn't look good. I am taking a look at it.

**Comment by enockseth** [comment]
Fixed via [osm-analytics #103](https://github.com/hotosm/osm-analytics/issues/103)
