### ISSUE TITLE
Differentiate city pages from website pages in menu

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/opencities#23]
In the website menu (top right), elements that link to city pages look the same as the _Home_, _About_, and _Resources_ pages. Maybe we can use a different style or offset it slightly to show the list of cities?

![screen shot 2018-07-25 at 15 35 16](https://user-images.githubusercontent.com/10201533/43204203-938c7cf0-9020-11e8-9919-6c03da1c602a.jpg)

**Comment by cgiovando** [comment]
Also from Grace:

> Could we have the cities be sub-headers under an Open Cities section instead of holding the same weight as Home, About, etc?

**Comment by ppasq** [comment]
Changed to this:
![screen shot 2018-08-02 at 17 16 32](https://user-images.githubusercontent.com/3024454/43593374-e9aa4524-9677-11e8-92a9-2c21d319c6c9.png)

**Comment by vdeparday** [comment]
Looks good
