### ISSUE TITLE
Attribute completeness analytics

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/opencities#25]
Following our discussion today, we agreed on reviewing sample data models from some cities to design how we could track completeness of map feature attributes.

For _Percent of Mapped features and Tags_ in theme 1 of #11 this could track and display how many features have complete attributes, showing progress in surveying those specific elements in the field. For example, if a team is mapping schools and the level of education they offer (e.g. primary, secondary, etc), by showing the percent of features that have the [`isced:level`](https://wiki.openstreetmap.org/wiki/Key:isced:level) key filled out with a value.

At the same time, these completeness indicators can help answering questions about data quality (theme 2 in #11 - analytics _Geometry and Tagging Quality_) showing the level of attribute completeness of data layers in the selected city extent.

@jessbeutler please post sample data models here when available

@tyrasd: let's start thinking how we can implement this on the OSMA side, or whether would be more efficient to source from osma-health

**Comment by jessbeutler** [comment]
@cgiovando You can find that draft data model [here](https://docs.google.com/document/d/1FJ86BMOnSKF5R3zQDUcn0bA-wkl2LHCgIPvtGc5ixUQ/edit?usp=sharing).

**Comment by vdeparday** [comment]
Would be good to review this one tomorrow in the discussion on reporting and QA/QC

**Comment by gracedoherty** [comment]
We currently have sections for: OSM stats, a completeness map, and a data quality map. Closing this issue for now. Can be reopened if more ideas form from QA/QC and M&E conversations this summer.
