### ISSUE TITLE
Update OSMA API sources

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/opencities#27]
@tyrasd is updating code and documentation in [osm-analytics-api](https://github.com/GFDRR/osm-analytics-api/pull/30) to use the more generic `api.osm-analytics.org` subdomain.

@ppasq can you check for any code in the OSMA widgets/integrations that may need to be updated to reflect the new API endpoint?

We probably also need to update [osm-analytics-charts](https://github.com/GFDRR/osm-analytics-charts) and [osm-analytics-wp-charts](https://github.com/GFDRR/osm-analytics-wp-charts)

**Comment by cgiovando** [comment]
@ppasq please list the files that will need to be updated with the new API endpoint once it's working - thanks!

**Comment by ppasq** [comment]
It probably needs to updated in [env.js](https://github.com/GFDRR/opencities/blob/master/js/env.js) only.
