### ISSUE TITLE
Add an export of the data on each city page

### ISSUE THREAD

**Issue by vdeparday** [GFDRR/opencities#40]
In the previous site, I had created some crafty overpass export which would likely not work but still we are going to have requests for the data often so we should have at least a link to some other export (HOT or other).

Even better, we should export it following the data model of the DIFD challenge so it can be used directly in modelling tools.

**Comment by vdeparday** [comment]
@cgiovando could you look into that as part of the work on analytics too? Once we have the AOIs and layers definition we should be able to do that no?

**Comment by vdeparday** [comment]
This and #116 should maybe part of a new section: Access to Data or something at the bottom or top of the page to keep it clean ?

**Comment by gracedoherty** [comment]
@cgiovando when you say create exports for the other cities, what does that entail? Determining AOI, feature selection options from data model, ..... ?

**Comment by cgiovando** [comment]
@gracedoherty AOIs are already determined [here](https://docs.google.com/document/d/1BVfSm_YwxiZD-G5kYSzjdNVnUgLo6DsF4AqjEutTEL0), but they may need to be checked/revised, to make sure we have the latest version. Brazzaville is also still missing.

With the latest GeoJSON file of each city, you can create new exports at https://export.hotosm.org/en/v3/exports/new

In the `Data` tab, you can interactively select features to export using the `Tag Tree`, or create a YAML file that matches the data model for each city. Here's an example of GED4ALL data schema: https://export.hotosm.org/en/v3/configurations/detail/dc1ce7fa-4cc8-4301-aaa9-0af182ee4969

![screen shot 2019-01-29 at 17 55 13](https://user-images.githubusercontent.com/10201533/52068067-34971600-257c-11e9-95e0-7505680da720.jpg)

Once you have all the exports ready, please post them here for @ppasq  to link on city pages - thanks!

**Comment by cgiovando** [comment]
Accra	https://export.hotosm.org/en/v3/exports/c650a0eb-4870-49ac-9e14-492544e21c40
Antananarivo	https://export.hotosm.org/en/v3/exports/57f6e97b-ef18-43cf-9191-b715df440185
Kampala	https://export.hotosm.org/en/v3/exports/7f29cb00-9469-471e-a78b-aa42eb1c5214
Kinshasa 	https://export.hotosm.org/en/v3/exports/3bcd8b93-fee3-42d1-b81b-1b3b37200cc2
Zanzibar	https://export.hotosm.org/en/v3/exports/7d24c924-1b58-4053-9037-4067355b0093
Monrovia	https://export.hotosm.org/en/v3/exports/b5b937a7-8db6-4d3d-865b-41a94eb38eae/
Ngaoundere	https://export.hotosm.org/v3/exports/07fe4f3c-b36f-44a2-bc77-0aab140f702d/
Pointe-Noire	https://export.hotosm.org/v3/exports/5c91e31f-4af7-4f9c-b557-78a675ec44ee/
Seychelles	https://export.hotosm.org/v3/exports/dfa5f3d2-b37c-4a51-9bb0-c00e788dd4db/
Saint Louis	https://export.hotosm.org/v3/exports/b9980666-d2b9-4452-9476-8e06a31eedc2/

**Comment by ppasq** [comment]
Done. Please open a new issue when Brazzaville data is available.
