### ISSUE TITLE
Point www.opencitiesproject.org to new website

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/opencities#5]
After #4 is done, point DNS to the new Github pages website

**Comment by cgiovando** [comment]
http://opencitiesproject.com is now pointing to the new website. Still waiting on access to .org

**Comment by ppasq** [comment]
Done. It may take a while to propagate.

**Comment by cgiovando** [comment]
Closed with https://github.com/GFDRR/opencities/commit/d4e528e20ba7d8f826be01b649eefcee667d3166
