### ISSUE TITLE
Map doesn't display the cities on Mobile

### ISSUE THREAD

**Issue by vdeparday** [GFDRR/opencities#55]

**Comment by ppasq** [comment]
Could you please provide some details?
If you mean the map in the home page I can see the city names displayed on iOS.

![img_2553](https://user-images.githubusercontent.com/3024454/44973821-1a6df300-af5e-11e8-9bd2-372c445b5afb.JPG)

**Comment by vdeparday** [comment]
Checking on my android phone it also works. It was on a participant phone.
The size was off, and the points were not visible.

**Comment by ppasq** [comment]
Since an interactive map was added could you please check if this issue can be closed?

**Comment by vdeparday** [comment]
The map is now displaying, however, I cannot tap on the cities? But that may be fine since there are links below ?

**Comment by vdeparday** [comment]
Sounds good
