### ISSUE TITLE
Add "Resources" page

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/opencities#7]
"Resources" page in the menu with content from http://www.opencitiesproject.org/guide/ and link to https://opencitiesafrica.course.tc/catalog/course/open-cities-africa

**Comment by ppasq** [comment]
A resource page has been added.

**Comment by cgiovando** [comment]
From Grace:

>Bold the words **Chapter 1**, **Chapter 2**, etc. in the bulleted list.

**Comment by ppasq** [comment]
Fixed with #34
